server:
  port: 9999

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pdf-service-db?createDatabaseIfNotExist=true
    username: root
    password: 0003pray
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        hbm2ddl.auto: update
        show_sql: true
        format_sql: true
