server:
  port: 9999

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springrestapi?createDatabaseIfNotExist=true
    username: root
    password: 0003pray
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
        hbm2ddl.auto: update